[package]
name = "argon2-hasher-cli"
authors = ["Tanner Davies <tanner.e.davies@protonmail.com>"]
version = "1.0.0"
edition = "2021"

[dependencies]
argon2-kdf = "1.3.0"
base64 = "0.21.4"
rpassword = "7.2.0"
zeroize = "1.6.0"


